/**
 * airports.js
 * Worldwide airport database for Hassni Ticket Company dashboard.
 * Add more airports by following the same object structure.
 * { iata, city, country, flag (2-letter ISO country code) }
 */

const AIRPORTS = [
  /* ── PAKISTAN ── */
  { iata:'LHE', city:'Lahore',         country:'Pakistan',     flag:'PK' },
  { iata:'KHI', city:'Karachi',        country:'Pakistan',     flag:'PK' },
  { iata:'ISB', city:'Islamabad',      country:'Pakistan',     flag:'PK' },
  { iata:'PEW', city:'Peshawar',       country:'Pakistan',     flag:'PK' },
  { iata:'MUX', city:'Multan',         country:'Pakistan',     flag:'PK' },
  { iata:'SKT', city:'Sialkot',        country:'Pakistan',     flag:'PK' },
  { iata:'LYP', city:'Faisalabad',     country:'Pakistan',     flag:'PK' },
  { iata:'SUL', city:'Sui',            country:'Pakistan',     flag:'PK' },
  { iata:'GWD', city:'Gwadar',         country:'Pakistan',     flag:'PK' },
  { iata:'UET', city:'Quetta',         country:'Pakistan',     flag:'PK' },

  /* ── UAE ── */
  { iata:'DXB', city:'Dubai',          country:'UAE',          flag:'AE' },
  { iata:'AUH', city:'Abu Dhabi',      country:'UAE',          flag:'AE' },
  { iata:'SHJ', city:'Sharjah',        country:'UAE',          flag:'AE' },
  { iata:'RKT', city:'Ras Al Khaimah', country:'UAE',          flag:'AE' },
  { iata:'FJR', city:'Fujairah',       country:'UAE',          flag:'AE' },

  /* ── SAUDI ARABIA ── */
  { iata:'RUH', city:'Riyadh',         country:'Saudi Arabia', flag:'SA' },
  { iata:'JED', city:'Jeddah',         country:'Saudi Arabia', flag:'SA' },
  { iata:'MED', city:'Madinah',        country:'Saudi Arabia', flag:'SA' },
  { iata:'DMM', city:'Dammam',         country:'Saudi Arabia', flag:'SA' },
  { iata:'AHB', city:'Abha',           country:'Saudi Arabia', flag:'SA' },
  { iata:'TIF', city:'Taif',           country:'Saudi Arabia', flag:'SA' },
  { iata:'HOF', city:'Al-Ahsa',        country:'Saudi Arabia', flag:'SA' },

  /* ── GULF / MIDDLE EAST ── */
  { iata:'DOH', city:'Doha',           country:'Qatar',        flag:'QA' },
  { iata:'MCT', city:'Muscat',         country:'Oman',         flag:'OM' },
  { iata:'SLL', city:'Salalah',        country:'Oman',         flag:'OM' },
  { iata:'KWI', city:'Kuwait City',    country:'Kuwait',       flag:'KW' },
  { iata:'BAH', city:'Bahrain',        country:'Bahrain',      flag:'BH' },
  { iata:'AMM', city:'Amman',          country:'Jordan',       flag:'JO' },
  { iata:'AQJ', city:'Aqaba',          country:'Jordan',       flag:'JO' },
  { iata:'BEY', city:'Beirut',         country:'Lebanon',      flag:'LB' },
  { iata:'CAI', city:'Cairo',          country:'Egypt',        flag:'EG' },
  { iata:'HRG', city:'Hurghada',       country:'Egypt',        flag:'EG' },
  { iata:'SSH', city:'Sharm El-Sheikh',country:'Egypt',        flag:'EG' },
  { iata:'DAM', city:'Damascus',       country:'Syria',        flag:'SY' },
  { iata:'BGW', city:'Baghdad',        country:'Iraq',         flag:'IQ' },
  { iata:'EBL', city:'Erbil',          country:'Iraq',         flag:'IQ' },
  { iata:'IKA', city:'Tehran',         country:'Iran',         flag:'IR' },
  { iata:'TLV', city:'Tel Aviv',       country:'Israel',       flag:'IL' },

  /* ── UK ── */
  { iata:'LHR', city:'London Heathrow',country:'UK',           flag:'GB' },
  { iata:'LGW', city:'London Gatwick', country:'UK',           flag:'GB' },
  { iata:'STN', city:'London Stansted',country:'UK',           flag:'GB' },
  { iata:'MAN', city:'Manchester',     country:'UK',           flag:'GB' },
  { iata:'BHX', city:'Birmingham',     country:'UK',           flag:'GB' },
  { iata:'GLA', city:'Glasgow',        country:'UK',           flag:'GB' },
  { iata:'EDI', city:'Edinburgh',      country:'UK',           flag:'GB' },
  { iata:'BRS', city:'Bristol',        country:'UK',           flag:'GB' },

  /* ── EUROPE ── */
  { iata:'CDG', city:'Paris CDG',      country:'France',       flag:'FR' },
  { iata:'ORY', city:'Paris Orly',     country:'France',       flag:'FR' },
  { iata:'NCE', city:'Nice',           country:'France',       flag:'FR' },
  { iata:'FRA', city:'Frankfurt',      country:'Germany',      flag:'DE' },
  { iata:'MUC', city:'Munich',         country:'Germany',      flag:'DE' },
  { iata:'BER', city:'Berlin',         country:'Germany',      flag:'DE' },
  { iata:'DUS', city:'Dusseldorf',     country:'Germany',      flag:'DE' },
  { iata:'AMS', city:'Amsterdam',      country:'Netherlands',  flag:'NL' },
  { iata:'MAD', city:'Madrid',         country:'Spain',        flag:'ES' },
  { iata:'BCN', city:'Barcelona',      country:'Spain',        flag:'ES' },
  { iata:'FCO', city:'Rome Fiumicino', country:'Italy',        flag:'IT' },
  { iata:'MXP', city:'Milan Malpensa', country:'Italy',        flag:'IT' },
  { iata:'VCE', city:'Venice',         country:'Italy',        flag:'IT' },
  { iata:'IST', city:'Istanbul',       country:'Turkey',       flag:'TR' },
  { iata:'SAW', city:'Istanbul Sabiha',country:'Turkey',       flag:'TR' },
  { iata:'AYT', city:'Antalya',        country:'Turkey',       flag:'TR' },
  { iata:'ZRH', city:'Zurich',         country:'Switzerland',  flag:'CH' },
  { iata:'GVA', city:'Geneva',         country:'Switzerland',  flag:'CH' },
  { iata:'VIE', city:'Vienna',         country:'Austria',      flag:'AT' },
  { iata:'BRU', city:'Brussels',       country:'Belgium',      flag:'BE' },
  { iata:'LIS', city:'Lisbon',         country:'Portugal',     flag:'PT' },
  { iata:'ATH', city:'Athens',         country:'Greece',       flag:'GR' },
  { iata:'CPH', city:'Copenhagen',     country:'Denmark',      flag:'DK' },
  { iata:'ARN', city:'Stockholm',      country:'Sweden',       flag:'SE' },
  { iata:'HEL', city:'Helsinki',       country:'Finland',      flag:'FI' },
  { iata:'OSL', city:'Oslo',           country:'Norway',       flag:'NO' },
  { iata:'WAW', city:'Warsaw',         country:'Poland',       flag:'PL' },
  { iata:'PRG', city:'Prague',         country:'Czech Republic',flag:'CZ'},
  { iata:'BUD', city:'Budapest',       country:'Hungary',      flag:'HU' },
  { iata:'DUB', city:'Dublin',         country:'Ireland',      flag:'IE' },
  { iata:'OTP', city:'Bucharest',      country:'Romania',      flag:'RO' },
  { iata:'SOF', city:'Sofia',          country:'Bulgaria',     flag:'BG' },

  /* ── USA / CANADA ── */
  { iata:'JFK', city:'New York JFK',   country:'USA',          flag:'US' },
  { iata:'EWR', city:'New York Newark',country:'USA',          flag:'US' },
  { iata:'LAX', city:'Los Angeles',    country:'USA',          flag:'US' },
  { iata:'ORD', city:'Chicago O\'Hare',country:'USA',          flag:'US' },
  { iata:'DFW', city:'Dallas',         country:'USA',          flag:'US' },
  { iata:'ATL', city:'Atlanta',        country:'USA',          flag:'US' },
  { iata:'MIA', city:'Miami',          country:'USA',          flag:'US' },
  { iata:'SFO', city:'San Francisco',  country:'USA',          flag:'US' },
  { iata:'BOS', city:'Boston',         country:'USA',          flag:'US' },
  { iata:'IAD', city:'Washington DC',  country:'USA',          flag:'US' },
  { iata:'YYZ', city:'Toronto',        country:'Canada',       flag:'CA' },
  { iata:'YVR', city:'Vancouver',      country:'Canada',       flag:'CA' },
  { iata:'YUL', city:'Montreal',       country:'Canada',       flag:'CA' },

  /* ── ASIA ── */
  { iata:'NRT', city:'Tokyo Narita',   country:'Japan',        flag:'JP' },
  { iata:'HND', city:'Tokyo Haneda',   country:'Japan',        flag:'JP' },
  { iata:'OSA', city:'Osaka',          country:'Japan',        flag:'JP' },
  { iata:'ICN', city:'Seoul Incheon',  country:'South Korea',  flag:'KR' },
  { iata:'PEK', city:'Beijing',        country:'China',        flag:'CN' },
  { iata:'PVG', city:'Shanghai',       country:'China',        flag:'CN' },
  { iata:'CAN', city:'Guangzhou',      country:'China',        flag:'CN' },
  { iata:'HKG', city:'Hong Kong',      country:'Hong Kong',    flag:'HK' },
  { iata:'SIN', city:'Singapore',      country:'Singapore',    flag:'SG' },
  { iata:'KUL', city:'Kuala Lumpur',   country:'Malaysia',     flag:'MY' },
  { iata:'BKK', city:'Bangkok Suvarnabhumi',country:'Thailand',flag:'TH'},
  { iata:'DMK', city:'Bangkok Don Mueang',country:'Thailand',  flag:'TH' },
  { iata:'CGK', city:'Jakarta',        country:'Indonesia',    flag:'ID' },
  { iata:'DPS', city:'Bali',           country:'Indonesia',    flag:'ID' },
  { iata:'MNL', city:'Manila',         country:'Philippines',  flag:'PH' },
  { iata:'SGN', city:'Ho Chi Minh City',country:'Vietnam',     flag:'VN' },
  { iata:'HAN', city:'Hanoi',          country:'Vietnam',      flag:'VN' },
  { iata:'RGN', city:'Yangon',         country:'Myanmar',      flag:'MM' },

  /* ── SOUTH ASIA ── */
  { iata:'DEL', city:'New Delhi',      country:'India',        flag:'IN' },
  { iata:'BOM', city:'Mumbai',         country:'India',        flag:'IN' },
  { iata:'BLR', city:'Bangalore',      country:'India',        flag:'IN' },
  { iata:'MAA', city:'Chennai',        country:'India',        flag:'IN' },
  { iata:'CCU', city:'Kolkata',        country:'India',        flag:'IN' },
  { iata:'HYD', city:'Hyderabad',      country:'India',        flag:'IN' },
  { iata:'AMD', city:'Ahmedabad',      country:'India',        flag:'IN' },
  { iata:'CMB', city:'Colombo',        country:'Sri Lanka',    flag:'LK' },
  { iata:'DAC', city:'Dhaka',          country:'Bangladesh',   flag:'BD' },
  { iata:'CGP', city:'Chittagong',     country:'Bangladesh',   flag:'BD' },
  { iata:'KTM', city:'Kathmandu',      country:'Nepal',        flag:'NP' },
  { iata:'MLE', city:'Maldives Male',  country:'Maldives',     flag:'MV' },

  /* ── CENTRAL ASIA ── */
  { iata:'TAS', city:'Tashkent',       country:'Uzbekistan',   flag:'UZ' },
  { iata:'ALA', city:'Almaty',         country:'Kazakhstan',   flag:'KZ' },
  { iata:'ASB', city:'Ashgabat',       country:'Turkmenistan', flag:'TM' },
  { iata:'KBL', city:'Kabul',          country:'Afghanistan',  flag:'AF' },

  /* ── AFRICA ── */
  { iata:'NBO', city:'Nairobi',        country:'Kenya',        flag:'KE' },
  { iata:'JNB', city:'Johannesburg',   country:'South Africa', flag:'ZA' },
  { iata:'CPT', city:'Cape Town',      country:'South Africa', flag:'ZA' },
  { iata:'LOS', city:'Lagos',          country:'Nigeria',      flag:'NG' },
  { iata:'ABV', city:'Abuja',          country:'Nigeria',      flag:'NG' },
  { iata:'ADD', city:'Addis Ababa',    country:'Ethiopia',     flag:'ET' },
  { iata:'CMN', city:'Casablanca',     country:'Morocco',      flag:'MA' },
  { iata:'TUN', city:'Tunis',          country:'Tunisia',      flag:'TN' },
  { iata:'ALG', city:'Algiers',        country:'Algeria',      flag:'DZ' },

  /* ── OCEANIA ── */
  { iata:'SYD', city:'Sydney',         country:'Australia',    flag:'AU' },
  { iata:'MEL', city:'Melbourne',      country:'Australia',    flag:'AU' },
  { iata:'BNE', city:'Brisbane',       country:'Australia',    flag:'AU' },
  { iata:'PER', city:'Perth',          country:'Australia',    flag:'AU' },
  { iata:'AKL', city:'Auckland',       country:'New Zealand',  flag:'NZ' },

  /* ── LATIN AMERICA ── */
  { iata:'GRU', city:'Sao Paulo',      country:'Brazil',       flag:'BR' },
  { iata:'GIG', city:'Rio de Janeiro', country:'Brazil',       flag:'BR' },
  { iata:'MEX', city:'Mexico City',    country:'Mexico',       flag:'MX' },
  { iata:'BOG', city:'Bogota',         country:'Colombia',     flag:'CO' },
  { iata:'EZE', city:'Buenos Aires',   country:'Argentina',    flag:'AR' },
  { iata:'LIM', city:'Lima',           country:'Peru',         flag:'PE' },
  { iata:'SCL', city:'Santiago',       country:'Chile',        flag:'CL' },
];
